- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 #3 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobWardenHelper
      time: 3600 #1 hrs # Corvax-WardHelp-NEXT
  weight: 6
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CanChokeGrab # Corvax-Next-Grab
      - type: Skills # Corvax-Next-Skills
        skills:
        - Shooting
        - ShuttleControl

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltSecurity # Corvax-Next-WardenHeadset
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
    - ClothingNeckSecBadgeWarden # Corvax-Next-Badges
